### ISSUE TITLE
Implicit declaration of functions sqlite3_key , sqlite3_rekey invalid in c99

### ISSUE THREAD

**Issue by YamunaChebolu** [sqlcipher/SQLCipherManager#3]
Getting this compiler error while running the project having SQLcipher. I have checked the sqlite3.h header file in Xcode 9 beta. But I didn't found the above declarations(sqlite3_key , sqlite3_rekey) in the header file.

**Comment by billymeltdown** [comment]
Hi @YamunaChebolu, sorry to hear about the trouble. 

To use this class you need to have SQLCipher's `sqlite3.h` file in your header search paths, and to link against SQLCipher's `libsqlcipher.a`, not the version of SQLite that is included with Xcode's SDKs. Without knowing how you are doing this it's hard to know what the problem might be. We've got some help on including SQLCipher in an Xcode project here:

https://www.zetetic.net/sqlcipher/ios-tutorial/

Are you adding `SQLCipherManager.h` and `SQLCipherManager.m` directly to your project, or are you using a cross-project reference to add `SQLCipherManager.xcodeproj` to your workspace? The latter might be more complicated to configure correctly than is warranted, it is much easier to include the two `SQLCipherManager` source files in your project directly.

I'm going to close this GitHub Issue for now—if the above suggestions don't help, please stop by our discussion forum at https://discuss.zetetic.net/c/sqlcipher/issues and let us know what settings aren't working for you.

**Comment by YamunaChebolu** [comment]
@billymeltdown 

Thanks fro the update.
I have added SQLCipherManager.h and SQLCipherManager.m files directly. I have gone through different blogs and every one is saying that, it seems you have missed to add "-DSQLITE_HAS_CODEC" in Other C Flags. But I have linked it properly and I can able to build my project successfully in Xcode 8 and previous versions. But I faced this issue in only Xcode 9 beta versions. I have verified the sqlite3.h file in both versions of Xcode(8 and 9) and found that the methods "sqlite3_key" and "sqlite3_rekey" were not exist in Xcode 9 version of sqlite3.h file. I think that's why I am getting these errors. 

Could you please check this and update ASAP.

Thanks in advance!

**Comment by billymeltdown** [comment]
How are you adding SQLCipher itself to your project? That sounds like it might be more the issue. I just created a new project, added my `libsqlcipher.a` to my Linked Libraries and Frameworks, adjusted my Header Search Paths setting to include the path to my `sqlite3.h`, added `-DSQLIte_HAS_CODEC` to the Other C Flags setting. Then I added the `SQLCipherManager.h|m` source files directly and I was able to create a manager object and key a database on build and run. I did this in Xcode 9 beta 1.

A couple more questions: Is it possible that you have another SQLite library linked to your project, e.g. `sqlite3.dylib`? Are you using CocoaPods?

**Comment by billymeltdown** [comment]
Another setting you might take a look at is Library Search Paths (although this should not be necessary if you add your `libsqlcipher.a` to your target the usual way). So, if my SQLCipher binary is in a subdirectory of my project, e.g. `sqlcipher-ios/binaries` I could add that path to the Library Search Paths build setting.

`LIBRARY_SEARCH_PATHS`:

> This is a list of paths to folders to be searched by the linker for libraries used by the product. Paths are delimited by whitespace, so any paths with spaces in them need to be properly quoted.
